/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoothRouteImport } from './routes/booth'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrintRouteImport } from './routes/print'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothRoute = BoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booth': typeof BoothRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/studio': typeof StudioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booth'
    | '/cabinet'
    | '/login'
    | '/print'
    | '/studio'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booth'
    | '/cabinet'
    | '/login'
    | '/print'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/booth'
    | '/cabinet'
    | '/login'
    | '/print'
    | '/studio'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoothRoute: typeof BoothRoute
  CabinetRoute: typeof CabinetRoute
  LoginRoute: typeof LoginRoute
  PrintRoute: typeof PrintRoute
  StudioRoute: typeof StudioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth': {
      id: '/booth'
      path: '/booth'
      fullPath: '/booth'
      preLoaderRoute: typeof BoothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoothRoute: BoothRoute,
  CabinetRoute: CabinetRoute,
  LoginRoute: LoginRoute,
  PrintRoute: PrintRoute,
  StudioRoute: StudioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
